In [1]:
import pandas as pd
import sqlite3
import os

# Ensure 'loaded' folder exists
os.makedirs('loaded', exist_ok=True)

In [2]:
# Load the transformed data
df_full = pd.read_csv('transformed/transformed_full.csv')
df_incremental = pd.read_csv('transformed/transformed_incremental.csv')

# Display preview
print("Full Data:")
display(df_full.head())

print("\nIncremental Data:")
display(df_incremental.head())

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8264\879162024.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_full = pd.read_csv('transformed/transformed_full.csv')

Full Data:

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,total_cost,order_week,order_day,product_name,product_detail,sales_bracket
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,48,2010-12-01,WHITE HANGING HEART T-LIGHT HOLDER,NaN,Very Low
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,48,2010-12-01,WHITE METAL LANTERN,NaN,Low
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,48,2010-12-01,CREAM CUPID HEARTS COAT HANGER,NaN,Low
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,48,2010-12-01,KNITTED UNION FLAG HOT WATER BOTTLE,NaN,Low
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,48,2010-12-01,RED WOOLLY HOTTIE WHITE HEART.,NaN,Low

Incremental Data:

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,total_cost,order_week,order_day,product_name,product_detail,sales_bracket
0,575317,23544,WALL ART MID CENTURY MODERN,2,2011-11-09 13:12:00,8.25,17402.0,United Kingdom,16.50,45,2011-11-09,WALL ART MID CENTURY MODERN,NaN,Very Low
1,575317,21790,VINTAGE SNAP CARDS,12,2011-11-09 13:12:00,0.85,17402.0,United Kingdom,10.20,45,2011-11-09,VINTAGE SNAP CARDS,NaN,Very Low
2,575317,21791,VINTAGE HEADS AND TAILS CARD GAME,12,2011-11-09 13:12:00,1.25,17402.0,United Kingdom,15.00,45,2011-11-09,VINTAGE HEADS AND TAILS CARD GAME,NaN,Very Low
3,575317,22619,SET OF 6 SOLDIER SKITTLES,80,2011-11-09 13:12:00,3.39,17402.0,United Kingdom,271.20,45,2011-11-09,SET OF 6 SOLDIER SKITTLES,NaN,Medium
4,575318,23318,BOX OF 6 MINI VINTAGE CRACKERS,12,2011-11-09 13:17:00,2.49,14921.0,United Kingdom,29.88,45,2011-11-09,BOX OF 6 MINI VINTAGE CRACKERS,NaN,Low

In [3]:
# Connect to SQLite database
conn_full = sqlite3.connect('loaded/full_data.db')
conn_inc = sqlite3.connect('loaded/incremental_data.db')

# Load dataframes into SQLite tables
df_full.to_sql('full_data', conn_full, if_exists='replace', index=False)
df_incremental.to_sql('incremental_data', conn_inc, if_exists='replace', index=False)

# Verify load
print("Full Data from SQLite:")
display(pd.read_sql('SELECT * FROM full_data LIMIT 5', conn_full))

print("\nIncremental Data from SQLite:")
display(pd.read_sql('SELECT * FROM incremental_data LIMIT 5', conn_inc))

# Close connections
conn_full.close()
conn_inc.close()

Full Data from SQLite:

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,total_cost,order_week,order_day,product_name,product_detail,sales_bracket
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,48,2010-12-01,WHITE HANGING HEART T-LIGHT HOLDER,None,Very Low
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,48,2010-12-01,WHITE METAL LANTERN,None,Low
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,48,2010-12-01,CREAM CUPID HEARTS COAT HANGER,None,Low
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,48,2010-12-01,KNITTED UNION FLAG HOT WATER BOTTLE,None,Low
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,48,2010-12-01,RED WOOLLY HOTTIE WHITE HEART.,None,Low

Incremental Data from SQLite:

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,total_cost,order_week,order_day,product_name,product_detail,sales_bracket
0,575317,23544,WALL ART MID CENTURY MODERN,2,2011-11-09 13:12:00,8.25,17402.0,United Kingdom,16.50,45,2011-11-09,WALL ART MID CENTURY MODERN,None,Very Low
1,575317,21790,VINTAGE SNAP CARDS,12,2011-11-09 13:12:00,0.85,17402.0,United Kingdom,10.20,45,2011-11-09,VINTAGE SNAP CARDS,None,Very Low
2,575317,21791,VINTAGE HEADS AND TAILS CARD GAME,12,2011-11-09 13:12:00,1.25,17402.0,United Kingdom,15.00,45,2011-11-09,VINTAGE HEADS AND TAILS CARD GAME,None,Very Low
3,575317,22619,SET OF 6 SOLDIER SKITTLES,80,2011-11-09 13:12:00,3.39,17402.0,United Kingdom,271.20,45,2011-11-09,SET OF 6 SOLDIER SKITTLES,None,Medium
4,575318,23318,BOX OF 6 MINI VINTAGE CRACKERS,12,2011-11-09 13:17:00,2.49,14921.0,United Kingdom,29.88,45,2011-11-09,BOX OF 6 MINI VINTAGE CRACKERS,None,Low